# Constants, Pin Definations and other settings

CW = 0
CCW = 1

# Base Motor
PUL_PIN_BASE = 22
DIR_PIN_BASE = 27
ENA_PIN_BASE = 17
GEAR_RATIO_BASE = 50
STEPS_PER_REV_BASE = 800
STEPS_PER_DEGREE_BASE = STEPS_PER_REV_BASE / 360

# Shoulder Motor
PUL_PIN_SHOULDER = 22
DIR_PIN_SHOULDER = 27
ENA_PIN_SHOULDER = 17
GEAR_RATIO_SHOULDER = 50
STEPS_PER_REV_SHOULDER = 800
STEPS_PER_DEGREE_SHOULDER = STEPS_PER_REV_SHOULDER / 360

# Elbow Motor
PUL_PIN_ELBOW = 22
DIR_PIN_ELBOW = 27
ENA_PIN_ELBOW = 17
GEAR_RATIO_ELBOW = 30
STEPS_PER_REV_ELBOW = 800
STEPS_PER_DEGREE_ELBOW = STEPS_PER_REV_ELBOW / 360

# Wrist Motor
PUL_PIN_WRIST = 22
DIR_PIN_WRIST = 27
ENA_PIN_WRIST = 17
GEAR_RATIO_WRIST = 1
STEPS_PER_REV_WRIST = 800
STEPS_PER_DEGREE_WRIST = STEPS_PER_REV_WRIST / 360

# Gripper Motor
PUL_PIN_GRIPPER = 22
DIR_PIN_GRIPPER = 27
ENA_PIN_GRIPPER = 17
GEAR_RATIO_GRIPPER = 1
STEPS_PER_REV_GRIPPER = 800
STEPS_PER_DEGREE_GRIPPER = STEPS_PER_REV_GRIPPER / 360

